ru:
  languageCode: ru-RU
  languageName: Русский
  contentDir: content/ru
  title: "Сунь Шэнцзе | Персональный сайт"
  weight: 1
en:
  languageCode: en-US
  languageName: English
  contentDir: content/en
  title: "Sun Shengjie | Personal website"
  weight: 2
